<?php

    /**
    |--------------------------------------------------------------------------
    | available ship names
    |--------------------------------------------------------------------------
    |
    | This config file contains all ship names. ships that are built get a name
    | via a randomly selected index.
    |
     */

return [

    /*
     * culture ship names
     * https://en.wikipedia.org/wiki/List_of_spacecraft_in_the_Culture_series
     */

    'Bora Horza Gobuchul',
    'Determinist',
    'Eschatologist (temporary name)',
    'Irregular Apocalypse',
    'No More Mr Nice Guy',
    'Profit Margin',
    'Nervous Energy',
    'Prosthetic Conscience',
    'Revisionist',
    'Trade Surplus',
    'The Ends Of Invention',
    'The Hand of God 137',
    'Clear Air Turbulence or \'CAT\' for short',
    'Control Surface',
    'Cargo Cult',
    'Little Rascal',
    'So Much For Subtlety',
    'Unfortunate Conflict Of Evidence',
    'Youthful Indiscretion',
    'Flexible Demeanour',
    'Just Read The Instructions',
    'Of Course I Still Love You',
    'Zealot',
    'Limiting Factor',
    'Gunboat Diplomat',
    'Kiss My Ass',
    'Prime Mover',
    'Screw Loose',
    'Invincible',
    'Bad For Business',
    'Ablation',
    'Arbitrary',
    'Arrested Development',
    'A Series Of Unlikely Explanations',
    'A Ship With A View',
    'Big Sexy Beast',
    'Boo!',
    'Cantankerous',
    'Credibility Problem',
    'Dramatic Exit',
    'Excuses And Accusations',
    'Funny, It Worked Last Time...',
    'God Told Me To Do It',
    'Halation Effect',
    'Happy Idiot Talk ',
    'Helpless In The Face Of Your Beauty',
    'Heresiarch',
    'I Thought He Was With You',
    'It\'ll Be Over By Christmas',
    'Just Another Victim Of The Ambient Morality',
    'Minority Report',
    'Never Talk To Strangers',
    'Not Wanted On Voyage',
    'Only Slightly Bent',
    'Perfidy',
    'Sacrificial Victim',
    'Space Monster',
    'Stranger Here Myself',
    'Synchronize Your Dogmas',
    'Thank You And Goodnight',
    'The Precise Nature Of The Catastrophe',
    'Ultimate Ship The Second',
    'Undesirable Alien',
    'Unwitting Accomplice',
    'Well I Was In The Neighbourhood',
    'You\'ll Thank Me Later',
    'You Would If You Really Loved Me',
    'Congenital Optimist',
    'Size Isn\'t Everything',
    'What Are The Civilian Applications?',
    'Just Testing',
    'Sweet and Full of Grace',
    'Very Little Gravitas Indeed',
    'Xenophobe',
    'Anticipation Of A New Lover\'s Arrival, The',
    'Death And Gravity',
    'Ethics Gradient',
    'Honest Mistake',
    'Limivorous',
    'Uninvited Guest',
    'Use Psychology',
    'What Is The Answer And Why?',
    'Wisdom Like Silence',
    'Yawning Angel',
    'Zero Gravitas',
    'Not Invented Here',
    'Misophist',
    'Serious Callers Only',
    'Steely Glint',
    'Different Tan',
    'Fate Amenable To Change',
    'Grey Area (aka Meatfucker)',
    'It\'s Character Forming',
    'Jaundiced Outlook',
    'Problem Child',
    'Reasonable Excuse',
    'Recent Convert',
    'Tactical Grace',
    'Unacceptable Behaviour',
    'Attitude Adjuster',
    'Heavy Messing',
    'Killing Time',
    'Frank Exchange Of Views',
    'T3OU 4',
    'T3OU 118',
    'T3OU 736',
    'Charitable View',
    'Just Passing Through',
    'I Blame My Mother',
    'I Blame Your Mother',
    'Full Refund (formerly MBU 604)',
    'Quietly Confident',
    'No Fixed Abode',
    'Highpoint',
    'Shoot Them Later',
    'Appeal To Reason',
    'Break Even',
    'Long View',
    'Peace Makes Plenty',
    'Sober Counsel',
    'Within Reason',
    'Frightspear',
    'Furious Purpose',
    'Kiss The Blade',
    'Riptalon',
    'SacSlicer II',
    'Wingclipper',
    'Xenoclast',
    'Experiencing A Significant Gravitas Shortfall',
    'Lasting Damage',
    'Lasting Damage I',
    'Lasting Damage II',
    'Sanctioned Parts List',
    'Grey Area (aka Meatfucker)',
    'Nuisance Value',
    'Resistance Is Character-Forming',
    'Vulgarian',
    'Someone Else\'s Problem',
    'Lacking That Small Match Temperament',
    'Poke It With A Stick',
    'I Said, I\'ve Got A Big Stick',
    'Hand Me The Gun And Ask Me Again',
    'But Who\'s Counting?',
    'Germane Riposte',
    'We Haven\'t Met But You\'re A Great Fan Of Mine',
    'All The Same, I Saw It First',
    'Ravished By The Sheer Implausibility Of That Last Statement',
    'Zero Credibility',
    'Charming But Irrational',
    'Demented But Determined',
    'You May Not Be The Coolest Person Here',
    'Lucid Nonsense',
    'Awkward Customer',
    'Thorough But... Unreliable',
    'Advanced Case Of Chronic Patheticism',
    'Another Fine Product From The Nonsense Factory',
    'Conventional Wisdom',
    'In One Ear',
    'Fine Till You Came Along',
    'I Blame The Parents',
    'Inappropriate Response',
    'A Momentary Lapse Of Sanity',
    'Lapsed Pacifist',
    'Reformed Nice Guy',
    'Pride Comes Before A Fall',
    'Injury Time',
    'Now Look What You\'ve Made Me Do',
    'Kiss This Then',
    'Winter Storm',
    'Piety',
    'Soulhaven',
    'Seed Drill',
    'Don\'t Try This At Home',
    'Xenoglossicist',
    'Subtle Shift In Emphasis',
    'Experiencing A Significant Gravitas Shortfall',
    'It\'s My Party And I\'ll Sing If I Want To',
    'Lightly Seared On The Reality Grill',
    'Pure Big Mad Boat Man',
    'Qualifier',
    'Transient Atmospheric Phenomenon',
    'You Naughty Monsters',
    'Eight Rounds Rapid',
    'You\'ll Clean That Up Before You Leave',
    'Now We Try It My Way',
    'Liveware Problem',
    'Now, Turning to Reason, & its Just Sweetness',
    'On First Seeing Jhiriit',
    'Fasilyce, Upon Waking',
    'Inspiral, Coalescence, Ringdown',
    'Hence the Fortress',
    'Hundredth Idiot, The',
    'Dressed Up To Party',
    'Pelagian',
    'Sense Amid Madness, Wit Amidst Folly',
    'Total Internal Reflection',
    'Armchair Traveller',
    'Bodhisattva, OAQS',
    'Falling Outside The Normal Moral Constraints',
    'No One Knows What The Dead Think',
    'Hylozoist',
    'The Usual But Etymologically Unsatisfactory',
    'Beastly To The Animals',
    'Fixed Grin',
    'Hidden Income',
    'Scar Glamour',
    'Labtebricolephile',
    'Me, I\'m Counting',
    'Messenger Of Truth',
    'Fractious Person',
    'Rubric Of Ruin',
    'Abundance Of Onslaught',
    'Vision Of Hope Surpassed',
    'Joiler Veppers (provisional name)',
    'Ucalegon',
    '8401.00 Partial Photic Boundary',
    'A Fine Disregard For Awkward Facts',
    'Contents May Differ',
    'Empiricist',
    'Just The Washing Instruction Chip In Life\'s Rich Tapestry',
    'Kakistocrat',
    'Teething Problems',
    'Unreliable Witness',
    'Passing By And Thought I\'d Drop In',
    'Pressure Drop',
    'You Call This Clean?',
    'Displacement Activity',
    'Warm, Considering',
    'Anything Legal Considered',
    'Beats Working',
    'Headcrash',
    'Questionable Ethics',
    'Xenocrat',
    'Caconym',
    'New Toy',
    'Rapid Random Response Unit',
    'Learned Response',
    'Outstanding Contribution To The Historical Process',
    'Refreshingly Unconcerned With The Vulgar Exigencies Of Veracity',
    'Value Judgement',
    'Zoologist',
    'Mistake Not…',
    'Smile Tolerantly',
    'Gelish-Oplule',
    'Uagren',
    'Churkun',
    'Iberre',
    'CH2OH.(CHOH)4.CHO',
    'Abalule-Sheliz',
    'Gellemtyan-Asool-Anafawaya',
    'Laskuil-Hliz',
    'Quiatrea-Anang',
    'Fulanya-Guang',
    'Melancholia Enshrines All Triumph',
    'Oceanic Dissonance',
    'Exaltation-Parsimony III',

    /*
     * Black Metal song titles
     */

    // Askereia
    'Gedanken',
    'Mit Raben Und Wolfen',
    'Aus Dem Vereisten Unterholz Verschneiter Wälder',
    'Des Waldes Frost\'ger Hauch',
    'Winternacht',
    'Dunkle Romantik',
    'Aaskereia',
    'Hexensabbat',
    'Verhasst',
    'Die Leichenhexe',
    'Die Waldteufel',
    'Mein Raum in der Finsternis',
    'Winter',
    'Pestritt zu Hel',
    'Der boshafte Geist',
    'Dort, wo das alte Böse ruht',
    'Der schwarze Wald',
    'Als der Blick erlosch',
    // Alcest
    'Printemps émeraude',
    'Souvenirs d\'un autre monde',
    'Les iris',
    'Ciel errant',
    'Sur l\'autre rive je t\'attendrai',
    'Tir nan og',
    'Ecailles de lune',
    'Percées de lumière',
    'Abysses',
    'Solar Song',
    'Sur l\'océan couleur de fer',
    'Autre temps (Album version)',
    'Là où naissent les couleurs nouvelles',
    'Les voyages de l\'âme',
    'Nous sommes l\'emeraude',
    'Beings of Light',
    'Faiseurs de mondes',
    'Havens',
    'Summer\'s Glory',
    'Les jardins de minuit',
    'Protection',
    'Sapphire',
    'L\'Île des Morts',
    'Le Miroir',
    'Spiritual Instinct',
    // Angantyr
    'En fjendes død',
    'Raukes ran',
    'Skyggespil',
    'Svig',
    'Ni lange nætter',
    'Arngrims armod',
    'Lænket',
    'I forfædres fodspor',
    'Vemods hjemstavn',
    'Forvist',
    'Fælles fjende',
    'Stille skarpe knive',
    'Skovens egne våben',
    'Ulykke er dit navn',
    'Visdoms virke',
    'Krageben',
    'Træl af tomme ord',
    'På sin moders grav',
    'Falbudt og forrådt',
    'Råddenskab i sortenmuld',
    // Behemoth
    'Sculpting the Throne Ov Seth',
    'Demigod',
    'Conquer All',
    'The Nephilim Rising',
    'Towards Babylon',
    'Before the Aeons Came',
    'Mysterium Conuinctionis (Hermanubis)',
    'Xul',
    'Slaves Shall Serve',
    'The Reign Ov Shemsu-Hor',
    'Blow Your Trumpets Gabriel',
    'Furor Divinus',
    'Messe Noire',
    'Ora Pro Nobis Lucifer',
    'Amen',
    'The Satanist',
    'Ben Sahar',
    'In The Absence Ov Light',
    'O Father O Satan O Sun!',
    'Solve',
    'Wolves Ov Siberia',
    'God = Dog',
    'Ecclesia Diabolica Catholica',
    'Bartzabel',
    'If Crucifixion Was Not Enough',
    'Angelvs XIII',
    'Sabbath Mater',
    'Havohej Pantocrator',
    'Rom 5:8',
    'We Are the Next 1000 Years',
    'Coagvla',
    // Belzebubs
    'Cathedrals of Mourning',
    'The Faustian Alchemist',
    'Blackened Call',
    'Acheron',
    'Nam Gloria Lucifer',
    'The Crowned Daughters',
    'Dark Mother',
    'The Werewolf Bride',
    'Pantheon of the Nightside Gods',
    'Nuns in the Purgatory',
    'Maleficarum - The Veil of the Moon Queen',
    // Caladan Brood
    'City of Azure Fire',
    'Echoes of Battle',
    'Wild Autumn Wind',
    'To Walk the Ashes of Dead Empires',
    'A Voice Born of Stone and Dust',
    'Book of the Fallen',
    // Dark Funeral
    'Ravenna Strigoi Mortii',
    'Enriched by Evil',
    'Thy Legions Come',
    'Evil Prevail',
    'Slava Satan',
    'The Black Winged Horde',
    'Vobiscum Satanas',
    'Ineffable King of Darkness',
    'Unchain My Soul',
    'As One We Shall Conquer',
    'Beast Above Man',
    'As I Ascend',
    'Temple of Ahriman',
    'The Eternal Eclipse',
    'To Carve Another Wound',
    'Nail Them to the Cross',
    'Where Shadows Forever Reign',
    // Darkthrone
    'Transilvanian Hunger',
    'Over Fjell Og Gjennom Torner',
    'Skald Au Satans Sol',
    'Slottet I Det Fjerne',
    'Graven Takeheimens Saler',
    'I En Hall Med Flesk Og Mjod',
    'As Flittermice As Satans Spys',
    'En As I Dype Skogen',
    'I Muffle Your Inner Choir',
    'The Hardship of the Scots',
    'Old Star',
    'Alp Man',
    'Duke of Gloat',
    'The Key Is Inside the Wall',
    // Dimmu Borgir
    'Blessing Upon The Throne Of Tyranny',
    'Kings Of The Carnival Creation',
    'Hybrid Stigmata',
    'Architecture Of Genocidal Nature',
    'Puritania',
    'Indoctrination',
    'The Mealstrom Mephisto',
    'Absolute Sole Right',
    'Sympozium',
    'Perfection Or Vanity-Outro',
    'Burn In Hell',
    'Allegiance',
    'Progenies Of The Great Apocalypse',
    'Lepers Among Us',
    'Vredesbyrd',
    'For The World To Dictate Our Death',
    'Blood Hunger Doctrine',
    'Allehelgens Dod I Helveds Rike',
    'Cataclysm Children',
    'Eradication Instincts Defined',
    'Unorthodox Manifesto',
    'Heavenly Perverse',
    'Xibir',
    'Born Treacherous',
    'Gateways',
    'Chess With The Abyss',
    'Dimmu Borgir',
    'Ritualist',
    'The Demiurge Molecule',
    'A Jewel Traced Through Coal',
    'Renewal',
    'Endings And Continuations',
    'The Unveiling',
    'Interdimensional Summit',
    'Ætheric',
    'Council of Wolves and Snakes',
    'The Empyrean Phoenix',
    'Lightbringer',
    'I Am Sovereign',
    'Archaic Correspondence',
    'Alpha Aeon Omega',
    'Rite of Passage',
    // Dissection
    'At The Fathomless Depths',
    'Night\'s Blood',
    'Unhallowed',
    'Where Dead Angels Lie',
    'Retribution - Storm of the Light\'s Bane',
    'Thorns of Crimson Death',
    'Soulreaper',
    'No Dreams Breed In Breathless Sleep',
    // Ellende
    'Am Sterbebett Der Zeit',
    'Ballade Auf Den Tod',
    'Verehrung',
    'Scherben',
    'Versprochen...',
    'Verachtung',
    'Am Ende Stirbst Du Allein',
    'Intro',
    'Augenblick',
    'Die Wege',
    'Ein Stück Verzweiflung',
    'Der Blick wird leer',
    'Liebkosung des Eiswinds',
    'Du wärst eine schöne Leiche',
    'Atemzug',
    // Harakiri for the Sky
    'Lungs Filled with Water',
    '02:19 AM, Psychosis',
    'From Yesterday to Ashes',
    'Drown in My Nihilism',
    'Dancing on Debris',
    'My Bones to the Sea',
    'Jhator',
    'Homecoming, Denied!',
    '69 Dead Birds for Utøya',
    'Parting',
    'Burning from Both Ends',
    'Panoptycon',
    'Nailgarden',
    'Gallows (Give \'Em Rope)',
    'Calling the Rain',
    'Funeral Dreams',
    'Thanatos',
    'This Life as a Dagger',
    'The Traces We Leave',
    'Viaticum',
    'Dry the River',
    'Bury Me',
    'Fire, Walk with Me',
    'The Graves We\'ve Dug',
    'You Are the Scars',
    'Heroin Waltz',
    'Tomb Omnia',
    'Stillborn',
    'Voidgazer',
    'Manifesto',
    // Horna
    'Vihan Tie',
    'Musta Temppeli',
    'Vala Pedolle',
    'Kirous Ja Malja',
    'Saastainen Kaste',
    'Kuoleva Lupaus',
    'Zythifer',
    'Kuilunhenki',
    // Inquisition
    'Embraced by the Unholy Powers of Death and Destruction',
    'Enshrouded by Cryptic Temples of the Cult',
    'Kill with Hate',
    'Rituals of Human Sacrifice for Lord Baal',
    'Invoking the Majestic Throne of Satan',
    'Hail the King of All Heathens',
    'The Realm of Shadows Shall Forever Reign',
    'For Lucifer My Blood',
    'Imperial Hymn for Our Master Satan',
    'Ancient Monumental War Hymn',
    'Nocturnal Gatherings and Wicked Rites',
    'Strike of the Morning Star',
    'Through the Infinite Sphere Our Majesty Shall Rise',
    'Infernal Evocation of Torment',
    'Where Darkness is Lord and Death the Beginning',
    'Nefarious Dismal Orations',
    'Enter the Cult',
    'Before the Symbol of Satan we Bow and Praise',
    // Shylmagoghnar
    'I Am the Abyss',
    'Emergence',
    'Edin in Ashes',
    'This World Shall Fall',
    'Squandered Paradise',
    'Eternal Forest',
    'The Cosmic Tide',
    'A New Dawn',
    'The Sun No Longer',
    'Transience',
    'The Dawn Of Motion',
    'As All Must Come To Pass',
    'This Shadow Of The Heart',
    'The Chosen Path',
    'No Child Of Man Could Follow',
    'Journey Through The Fog',
    'Life',
    // Sojourner
    'Winter\'s Slumber',
    'Titan',
    'Ode to the Sovereign',
    'An Oath Sworn in Sorrow',
    'Our Bones Among the Ruins',
    'Where Lost Hope Lies',
    'The Shadowed Road',
    'The Monolith',
    'Eulogy for the Lost',
    'The Apocalyptic Theater',
    'Talas',
    'Fatal Frame',
    'The Deluge',
    'Atonement',
    'The Event Horizon',
    // Summoning
    'Evernight',
    'Flammifer',
    'Old Mornings Dawn',
    'The White Tower',
    'Caradhras',
    'Of Pale White Morns and Darkened Eves',
    'The Wandering Fire',
    'Earthshine',
    'Tar-Calion',
    'Silvertine',
    'Carcharoth',
    'Herumor',
    'Barrow-downs',
    'Night Fell Behind',
    'Mirklands',
    'With Doom I Come',
    // Veldes
    'Through the Bitter Flame',
    'Featherless Across the Burnt Skies',
    'Earth As a Nest of Bones and Debris',
    'Within These Roots Only Sickness Dwells',
    'Beneath the Grieving Waters',
    'The Roamer\'s Curse',
    'Void Path King',
    'To Ruins Of Throneless Realm',
    'Dust Scatterer',
    'Crowned In Oblivion',
    'The Bitterness Prophecy',
    'Seeking the Land Beyond',
    'Thorn Gatherer',
    'Ancient Remedy',
    'Hollow Antlers',
    'If Horizons Bled Out',
    'Keeper of the Flameless',
    'Lore of Forgotten Despair',
    'The Breeze Among Felled Trees',
    'This Light Was Never Meant To Be',
    // vvilderness
    'Starless Dark',
    'Sól',
    'Devour The Sun',
    'Life',
    'New Earth',
    'Aftershine',
    'Dark Waters',
    'Danu\'s Tears',
    'Mist Pillars \'19',
    'It Comes With The Rain',
    'Havasok / Snowy Mountains',
    'Wilderness',
];
