<?php

    /**
    |--------------------------------------------------------------------------
    | available ship names
    |--------------------------------------------------------------------------
    |
    | This config file contains all ship names. ships that are built get a name
    | via a randomly selected index.
    |
     */

return [

    /*
     * culture ship names
     * https://en.wikipedia.org/wiki/List_of_spacecraft_in_the_Culture_series
     */

    'Bora Horza Gobuchul',
    'Determinist',
    'Eschatologist (temporary name)',
    'Irregular Apocalypse',
    'No More Mr Nice Guy',
    'Profit Margin',
    'Nervous Energy',
    'Prosthetic Conscience',
    'Revisionist',
    'Trade Surplus',
    'The Ends Of Invention',
    'The Hand of God 137',
    'Clear Air Turbulence or \'CAT\' for short',
    'Control Surface',
    'Cargo Cult',
    'Little Rascal',
    'So Much For Subtlety',
    'Unfortunate Conflict Of Evidence',
    'Youthful Indiscretion',
    'Flexible Demeanour',
    'Just Read The Instructions',
    'Of Course I Still Love You',
    'Zealot',
    'Limiting Factor',
    'Gunboat Diplomat',
    'Kiss My Ass',
    'Prime Mover',
    'Screw Loose',
    'Invincible',
    'Bad For Business',
    'Ablation',
    'Arbitrary',
    'Arrested Development',
    'A Series Of Unlikely Explanations',
    'A Ship With A View',
    'Big Sexy Beast',
    'Boo!',
    'Cantankerous',
    'Credibility Problem',
    'Dramatic Exit',
    'Excuses And Accusations',
    'Funny, It Worked Last Time...',
    'God Told Me To Do It',
    'Halation Effect',
    'Happy Idiot Talk ',
    'Helpless In The Face Of Your Beauty',
    'Heresiarch',
    'I Thought He Was With You',
    'It\'ll Be Over By Christmas',
    'Just Another Victim Of The Ambient Morality',
    'Minority Report',
    'Never Talk To Strangers',
    'Not Wanted On Voyage',
    'Only Slightly Bent',
    'Perfidy',
    'Sacrificial Victim',
    'Space Monster',
    'Stranger Here Myself',
    'Synchronize Your Dogmas',
    'Thank You And Goodnight',
    'The Precise Nature Of The Catastrophe',
    'Ultimate Ship The Second',
    'Undesirable Alien',
    'Unwitting Accomplice',
    'Well I Was In The Neighbourhood',
    'You\'ll Thank Me Later',
    'You Would If You Really Loved Me',
    'Congenital Optimist',
    'Size Isn\'t Everything',
    'What Are The Civilian Applications?',
    'Just Testing',
    'Sweet and Full of Grace',
    'Very Little Gravitas Indeed',
    'Xenophobe',
    'Anticipation Of A New Lover\'s Arrival, The',
    'Death And Gravity',
    'Ethics Gradient',
    'Honest Mistake',
    'Limivorous',
    'Uninvited Guest',
    'Use Psychology',
    'What Is The Answer And Why?',
    'Wisdom Like Silence',
    'Yawning Angel',
    'Zero Gravitas',
    'Not Invented Here',
    'Misophist',
    'Serious Callers Only',
    'Steely Glint',
    'Different Tan',
    'Fate Amenable To Change',
    'Grey Area (aka Meatfucker)',
    'It\'s Character Forming',
    'Jaundiced Outlook',
    'Problem Child',
    'Reasonable Excuse',
    'Recent Convert',
    'Tactical Grace',
    'Unacceptable Behaviour',
    'Attitude Adjuster',
    'Heavy Messing',
    'Killing Time',
    'Frank Exchange Of Views',
    'T3OU 4',
    'T3OU 118',
    'T3OU 736',
    'Charitable View',
    'Just Passing Through',
    'I Blame My Mother',
    'I Blame Your Mother',
    'Full Refund (formerly MBU 604)',
    'Quietly Confident',
    'No Fixed Abode',
    'Highpoint',
    'Shoot Them Later',
    'Appeal To Reason',
    'Break Even',
    'Long View',
    'Peace Makes Plenty',
    'Sober Counsel',
    'Within Reason',
    'Frightspear',
    'Furious Purpose',
    'Kiss The Blade',
    'Riptalon',
    'SacSlicer II',
    'Wingclipper',
    'Xenoclast',
    'Experiencing A Significant Gravitas Shortfall',
    'Lasting Damage',
    'Lasting Damage I',
    'Lasting Damage II',
    'Sanctioned Parts List',
    'Nuisance Value',
    'Resistance Is Character-Forming',
    'Vulgarian',
    'Someone Else\'s Problem',
    'Lacking That Small Match Temperament',
    'Poke It With A Stick',
    'I Said, I\'ve Got A Big Stick',
    'Hand Me The Gun And Ask Me Again',
    'But Who\'s Counting?',
    'Germane Riposte',
    'We Haven\'t Met But You\'re A Great Fan Of Mine',
    'All The Same, I Saw It First',
    'Ravished By The Sheer Implausibility Of That Last Statement',
    'Zero Credibility',
    'Charming But Irrational',
    'Demented But Determined',
    'You May Not Be The Coolest Person Here',
    'Lucid Nonsense',
    'Awkward Customer',
    'Thorough But... Unreliable',
    'Advanced Case Of Chronic Patheticism',
    'Another Fine Product From The Nonsense Factory',
    'Conventional Wisdom',
    'In One Ear',
    'Fine Till You Came Along',
    'I Blame The Parents',
    'Inappropriate Response',
    'A Momentary Lapse Of Sanity',
    'Lapsed Pacifist',
    'Reformed Nice Guy',
    'Pride Comes Before A Fall',
    'Injury Time',
    'Now Look What You\'ve Made Me Do',
    'Kiss This Then',
    'Winter Storm',
    'Piety',
    'Soulhaven',
    'Seed Drill',
    'Don\'t Try This At Home',
    'Xenoglossicist',
    'Subtle Shift In Emphasis',
    'It\'s My Party And I\'ll Sing If I Want To',
    'Lightly Seared On The Reality Grill',
    'Pure Big Mad Boat Man',
    'Qualifier',
    'Transient Atmospheric Phenomenon',
    'You Naughty Monsters',
    'Eight Rounds Rapid',
    'You\'ll Clean That Up Before You Leave',
    'Now We Try It My Way',
    'Liveware Problem',
    'Now, Turning to Reason, & its Just Sweetness',
    'On First Seeing Jhiriit',
    'Fasilyce, Upon Waking',
    'Inspiral, Coalescence, Ringdown',
    'Hence the Fortress',
    'Hundredth Idiot, The',
    'Dressed Up To Party',
    'Pelagian',
    'Sense Amid Madness, Wit Amidst Folly',
    'Total Internal Reflection',
    'Armchair Traveller',
    'Bodhisattva, OAQS',
    'Falling Outside The Normal Moral Constraints',
    'No One Knows What The Dead Think',
    'Hylozoist',
    'The Usual But Etymologically Unsatisfactory',
    'Beastly To The Animals',
    'Fixed Grin',
    'Hidden Income',
    'Scar Glamour',
    'Labtebricolephile',
    'Me, I\'m Counting',
    'Messenger Of Truth',
    'Fractious Person',
    'Rubric Of Ruin',
    'Abundance Of Onslaught',
    'Vision Of Hope Surpassed',
    'Joiler Veppers (provisional name)',
    'Ucalegon',
    '8401.00 Partial Photic Boundary',
    'A Fine Disregard For Awkward Facts',
    'Contents May Differ',
    'Empiricist',
    'Just The Washing Instruction Chip In Life\'s Rich Tapestry',
    'Kakistocrat',
    'Teething Problems',
    'Unreliable Witness',
    'Passing By And Thought I\'d Drop In',
    'Pressure Drop',
    'You Call This Clean?',
    'Displacement Activity',
    'Warm, Considering',
    'Anything Legal Considered',
    'Beats Working',
    'Headcrash',
    'Questionable Ethics',
    'Xenocrat',
    'Caconym',
    'New Toy',
    'Rapid Random Response Unit',
    'Learned Response',
    'Outstanding Contribution To The Historical Process',
    'Refreshingly Unconcerned With The Vulgar Exigencies Of Veracity',
    'Value Judgement',
    'Zoologist',
    'Mistake Not…',
    'Smile Tolerantly',
    'Gelish-Oplule',
    'Uagren',
    'Churkun',
    'Iberre',
    'CH2OH.(CHOH)4.CHO',
    'Abalule-Sheliz',
    'Gellemtyan-Asool-Anafawaya',
    'Laskuil-Hliz',
    'Quiatrea-Anang',
    'Fulanya-Guang',
    'Melancholia Enshrines All Triumph',
    'Oceanic Dissonance',
    'Exaltation-Parsimony III',

    /*
     * Song titles
     */

    // Askereia
    'Gedanken',
    'Mit Raben Und Wolfen',
    'Aus Dem Vereisten Unterholz Verschneiter Wälder',
    'Des Waldes Frost\'ger Hauch',
    'Winternacht',
    'Dunkle Romantik',
    'Aaskereia',
    'Hexensabbat',
    'Verhasst',
    'Die Leichenhexe',
    'Die Waldteufel',
    'Mein Raum in der Finsternis',
    'Winter',
    'Pestritt zu Hel',
    'Der boshafte Geist',
    'Dort, wo das alte Böse ruht',
    'Der schwarze Wald',
    'Als der Blick erlosch',
    // Alcest
    'Printemps émeraude',
    'Souvenirs d\'un autre monde',
    'Les iris',
    'Ciel errant',
    'Sur l\'autre rive je t\'attendrai',
    'Tir nan og',
    'Ecailles de lune',
    'Percées de lumière',
    'Abysses',
    'Solar Song',
    'Sur l\'océan couleur de fer',
    'Autre temps (Album version)',
    'Là où naissent les couleurs nouvelles',
    'Les voyages de l\'âme',
    'Nous sommes l\'emeraude',
    'Beings of Light',
    'Faiseurs de mondes',
    'Havens',
    'Summer\'s Glory',
    'Les jardins de minuit',
    'Protection',
    'Sapphire',
    'L\'Île des Morts',
    'Le Miroir',
    'Spiritual Instinct',
    // Angantyr
    'En fjendes død',
    'Raukes ran',
    'Skyggespil',
    'Svig',
    'Ni lange nætter',
    'Arngrims armod',
    'Lænket',
    'I forfædres fodspor',
    'Vemods hjemstavn',
    'Forvist',
    'Fælles fjende',
    'Stille skarpe knive',
    'Skovens egne våben',
    'Ulykke er dit navn',
    'Visdoms virke',
    'Krageben',
    'Træl af tomme ord',
    'På sin moders grav',
    'Falbudt og forrådt',
    'Råddenskab i sortenmuld',
    // Behemoth
    'Sculpting the Throne Ov Seth',
    'Demigod',
    'Conquer All',
    'The Nephilim Rising',
    'Towards Babylon',
    'Before the Aeons Came',
    'Mysterium Conuinctionis',
    'Xul',
    'Slaves Shall Serve',
    'The Reign Ov Shemsu-Hor',
    'Blow Your Trumpets Gabriel',
    'Furor Divinus',
    'Messe Noire',
    'Ora Pro Nobis Lucifer',
    'The Satanist',
    'Ben Sahar',
    'In The Absence Ov Light',
    'O Father O Satan O Sun!',
    'Solve',
    'Wolves Ov Siberia',
    'God = Dog',
    'Ecclesia Diabolica Catholica',
    'Bartzabel',
    'If Crucifixion Was Not Enough',
    'Angelvs XIII',
    'Sabbath Mater',
    'Havohej Pantocrator',
    'Rom 5:8',
    'We Are the Next 1000 Years',
    'Coagvla',
    // Belzebubs
    'Cathedrals of Mourning',
    'The Faustian Alchemist',
    'Blackened Call',
    'Acheron',
    'Nam Gloria Lucifer',
    'The Crowned Daughters',
    'Dark Mother',
    'The Werewolf Bride',
    'Pantheon of the Nightside Gods',
    'Nuns in the Purgatory',
    'Maleficarum - The Veil of the Moon Queen',
    // Caladan Brood
    'City of Azure Fire',
    'Echoes of Battle',
    'Wild Autumn Wind',
    'To Walk the Ashes of Dead Empires',
    'A Voice Born of Stone and Dust',
    'Book of the Fallen',
    // Dark Funeral
    'Ravenna Strigoi Mortii',
    'Enriched by Evil',
    'Thy Legions Come',
    'Evil Prevail',
    'Slava Satan',
    'The Black Winged Horde',
    'Vobiscum Satanas',
    'Ineffable King of Darkness',
    'Unchain My Soul',
    'As One We Shall Conquer',
    'Beast Above Man',
    'As I Ascend',
    'Temple of Ahriman',
    'The Eternal Eclipse',
    'To Carve Another Wound',
    'Nail Them to the Cross',
    'Where Shadows Forever Reign',
    // Darkthrone
    'Transilvanian Hunger',
    'Over Fjell Og Gjennom Torner',
    'Skald Au Satans Sol',
    'Slottet I Det Fjerne',
    'Graven Takeheimens Saler',
    'I En Hall Med Flesk Og Mjod',
    'As Flittermice As Satans Spys',
    'En As I Dype Skogen',
    'I Muffle Your Inner Choir',
    'The Hardship of the Scots',
    'Old Star',
    'Alp Man',
    'Duke of Gloat',
    'The Key Is Inside the Wall',
    // Dimmu Borgir
    'Blessing Upon The Throne Of Tyranny',
    'Kings Of The Carnival Creation',
    'Hybrid Stigmata',
    'Architecture Of Genocidal Nature',
    'Puritania',
    'Indoctrination',
    'The Mealstrom Mephisto',
    'Absolute Sole Right',
    'Sympozium',
    'Burn In Hell',
    'Allegiance',
    'Progenies Of The Great Apocalypse',
    'Lepers Among Us',
    'Vredesbyrd',
    'For The World To Dictate Our Death',
    'Blood Hunger Doctrine',
    'Allehelgens Dod I Helveds Rike',
    'Cataclysm Children',
    'Eradication Instincts Defined',
    'Unorthodox Manifesto',
    'Heavenly Perverse',
    'Xibir',
    'Born Treacherous',
    'Gateways',
    'Chess With The Abyss',
    'Dimmu Borgir',
    'Ritualist',
    'The Demiurge Molecule',
    'A Jewel Traced Through Coal',
    'Renewal',
    'Endings And Continuations',
    'The Unveiling',
    'Interdimensional Summit',
    'Ætheric',
    'Council of Wolves and Snakes',
    'The Empyrean Phoenix',
    'Lightbringer',
    'I Am Sovereign',
    'Archaic Correspondence',
    'Alpha Aeon Omega',
    'Rite of Passage',
    // Dissection
    'At The Fathomless Depths',
    'Night\'s Blood',
    'Unhallowed',
    'Where Dead Angels Lie',
    'Retribution - Storm of the Light\'s Bane',
    'Thorns of Crimson Death',
    'Soulreaper',
    'No Dreams Breed In Breathless Sleep',
    // Ellende
    'Am Sterbebett Der Zeit',
    'Ballade Auf Den Tod',
    'Verehrung',
    'Scherben',
    'Versprochen...',
    'Verachtung',
    'Am Ende Stirbst Du Allein',
    'Intro',
    'Augenblick',
    'Die Wege',
    'Ein Stück Verzweiflung',
    'Der Blick wird leer',
    'Liebkosung des Eiswinds',
    'Du wärst eine schöne Leiche',
    'Atemzug',
    // Harakiri for the Sky
    'Lungs Filled with Water',
    '02:19 AM, Psychosis',
    'From Yesterday to Ashes',
    'Drown in My Nihilism',
    'Dancing on Debris',
    'My Bones to the Sea',
    'Jhator',
    'Homecoming, Denied!',
    '69 Dead Birds for Utøya',
    'Parting',
    'Burning from Both Ends',
    'Panoptycon',
    'Nailgarden',
    'Gallows (Give \'Em Rope)',
    'Calling the Rain',
    'Funeral Dreams',
    'Thanatos',
    'This Life as a Dagger',
    'The Traces We Leave',
    'Viaticum',
    'Dry the River',
    'Bury Me',
    'Fire, Walk with Me',
    'The Graves We\'ve Dug',
    'You Are the Scars',
    'Heroin Waltz',
    'Tomb Omnia',
    'Stillborn',
    'Voidgazer',
    'Manifesto',
    // Horna
    'Vihan Tie',
    'Musta Temppeli',
    'Vala Pedolle',
    'Kirous Ja Malja',
    'Saastainen Kaste',
    'Kuoleva Lupaus',
    'Zythifer',
    'Kuilunhenki',
    // Inquisition
    'Embraced by the Unholy Powers of Death and Destruction',
    'Enshrouded by Cryptic Temples of the Cult',
    'Kill with Hate',
    'Rituals of Human Sacrifice for Lord Baal',
    'Invoking the Majestic Throne of Satan',
    'Hail the King of All Heathens',
    'The Realm of Shadows Shall Forever Reign',
    'For Lucifer My Blood',
    'Imperial Hymn for Our Master Satan',
    'Ancient Monumental War Hymn',
    'Nocturnal Gatherings and Wicked Rites',
    'Strike of the Morning Star',
    'Through the Infinite Sphere Our Majesty Shall Rise',
    'Infernal Evocation of Torment',
    'Where Darkness is Lord and Death the Beginning',
    'Nefarious Dismal Orations',
    'Enter the Cult',
    'Before the Symbol of Satan we Bow and Praise',
    // Shylmagoghnar
    'I Am the Abyss',
    'Emergence',
    'Edin in Ashes',
    'This World Shall Fall',
    'Squandered Paradise',
    'Eternal Forest',
    'The Cosmic Tide',
    'A New Dawn',
    'The Sun No Longer',
    'Transience',
    'The Dawn Of Motion',
    'As All Must Come To Pass',
    'This Shadow Of The Heart',
    'The Chosen Path',
    'No Child Of Man Could Follow',
    'Journey Through The Fog',
    'Life',
    // Sojourner
    'Bound by Blood',
    'Heritage of the Natural Realm',
    'Aeons of Valor',
    'The Pale Host',
    'Homeward',
    'Trails of the Earth',
    'Empires of Ash',
    'Winter\'s Slumber',
    'Titan',
    'Ode to the Sovereign',
    'An Oath Sworn in Sorrow',
    'Our Bones Among the Ruins',
    'Where Lost Hope Lies',
    'The Shadowed Road',
    'The Monolith',
    'Eulogy for the Lost',
    'The Apocalyptic Theater',
    'Talas',
    'Fatal Frame',
    'The Deluge',
    'The Event Horizon',
    // Summoning
    'Evernight',
    'Flammifer',
    'Old Mornings Dawn',
    'The White Tower',
    'Caradhras',
    'Of Pale White Morns and Darkened Eves',
    'The Wandering Fire',
    'Earthshine',
    'Tar-Calion',
    'Silvertine',
    'Carcharoth',
    'Herumor',
    'Barrow-downs',
    'Night Fell Behind',
    'Mirklands',
    'With Doom I Come',
    // Veldes
    'Through the Bitter Flame',
    'Featherless Across the Burnt Skies',
    'Earth As a Nest of Bones and Debris',
    'Within These Roots Only Sickness Dwells',
    'Beneath the Grieving Waters',
    'The Roamer\'s Curse',
    'Void Path King',
    'To Ruins Of Throneless Realm',
    'Dust Scatterer',
    'Crowned In Oblivion',
    'The Bitterness Prophecy',
    'Seeking the Land Beyond',
    'Thorn Gatherer',
    'Ancient Remedy',
    'Hollow Antlers',
    'If Horizons Bled Out',
    'Keeper of the Flameless',
    'Lore of Forgotten Despair',
    'The Breeze Among Felled Trees',
    'This Light Was Never Meant To Be',
    // vvilderness
    'Starless Dark',
    'Sól',
    'Devour The Sun',
    'New Earth',
    'Aftershine',
    'Dark Waters',
    'Danu\'s Tears',
    'Mist Pillars \'19',
    'It Comes With The Rain',
    'Havasok / Snowy Mountains',
    'Wilderness',
	// YOB
	'Burning the Altar',
	'The Lie that is Sin',
	'Silence of Heaven',
	'Breathing from the Shallows',
	'The Great Cessation',
	'Blessed by Nothing',
	'Pain like Sugar',
	'Prepare The Ground',
	'Atma',
	'Before We Dreamed Of Two',
	'Upon The Sight Of The Other Shore',
	'Adrift In The Ocean',
	'In Our Blood',
	'Nothing to Win',
	'Unmask the Spectre',
	'Marrow',
	'Ablaze',
	'The Screen',
	'In Reverie',
	'Lungs Reach',
	'Beauty in Falling Leaves',
	'Original Face',
	'Our Raw Heart',
	// Opeth
	'Bleak',
	'Harvest',
	'The Drapery Falls',
	'Dirge for November',
	'The Funeral Portrait',
	'Patterns in the Ivy',
	'Blackwater Park',
	'The Leper Affinity',
	'Ghost of Perdition',
	'The Baying of the Hounds',
	'Beneath the Mire',
	'Atonement',
	'Reverie / Harlequin Forest',
	'Hours of Wealth',
	'The Grand Conjuration',
	'Isolation Years',
	// The Gathering
	'Saturnine',
	'Strange Machines',
	'Meltdown',
	'Nighttime Birds',
	'The Mirror Waters',
	'King For A Day',
	'Even The Spirits Are Afraid',
	'Broken Glass',
	'Heroes For Ghosts',
	'Afterwords',
	'Amity',
	'On Most Surfaces (Inuit)',
	'Paper Waves',
	'Leaves',
	'In Motion I',
	'Travel',
	'Waking Hour',
	'I Can See Four Miles',
	// Cattle Decapitation
	'Anthropogenic End Transmission',
	'The Geocide',
	'Be Still Our Bleeding Hearts',
	'Vulturous',
	'The Great Dying, Pt. 1',
	'One Day Closer to the End of the World',
	'Bring Back the Plague',
	'Absolute Destitute',
	'The Great Dying, Pt. 2',
	'Finish Them',
	'With All Disrespect',
	'Time\'s Cruel Curtain',
	'The Unerasable Past',
	'Death Atlas',
	// Gojira
	'Ocean planet',
	'Backbone',
	'From the sky',
	'Unicorn',
	'Where dragons dwell',
	'The haviest matter of the universe',
	'Flying whales',
	'In the wilderness',
	'World to come',
	'From mars',
	'To sirius',
	'Global warming',
	'Oroborus',
	'Toxic Garbage Island',
	'A Sight To Behold',
	'Yama\'s Messengers',
	'The Silver Cord',
	'All The Tears',
	'Adoration For None',
	'The Art Of Dying',
	'Esoteric Surgery',
	'Vacuity',
	'Wolf Down The Earth',
	'The Way Of All Flesh',
	'Explosia',
	'L\'Enfant Sauvage',
	'The Axe',
	'Liquid Fire',
	'The Wild Healer',
	'Planned Obsolescence',
	'Mouth Of Kala',
	'The Gift Of Guilt',
	'Pain Is A Master',
	'Born In Winter',
	'The Fall',
	'This Emptiness',
	'My Last Creation',
	'The Shooting Star',
	'Silvera',
	'The Cell',
	'Stranded',
	'Yellow Stone',
	'Magma',
	'Pray',
	'Only Pain',
	'Low Lands',
	'Liberation',
    // Type O Negative
    'Machine Screw',
    'Christian Woman',
    'Black No. 1 ',
    'Little Miss Scare-All',
    'Fay Wray Come Out And Play',
    'Kill All The White People',
    'Summer Breeze',
    'Set Me On Fire',
    'Dark Side Of The Womb',
    'We Hate Everyone',
    'Bloody Kisses',
    '3.O.I.F.',
    'Too Late_ Frozen',
    'Blood & Fire',
    'Can\'t Lose You',
    'Bad Ground',
    'Love You to Death',
    'Be My Druidess',
    'Green Man',
    'Red Water',
    'My Girlfriend\'s Girlfriend',
    'Die with Me',
    'Burnt Flowers Fallen',
    'In Praise of Bacchus',
    'Cinnamon Girl',
    'The Glorious Liberation of the People\'s Technocratic Republic of Vinnland',
    'Wolf Moon',
    'Haunted',
    'Thir13teen',
    'I Don\'t Wanna Be Me',
    'Less Than Zero',
    'Todd\'s Ship Gods (Above All Things)',
    'I Like Goils',
    '...A Dish Best Served Coldly',
    'How Could She_',
    'Life Is Killing Me',
    'Nettie',
    '(We Were) Electrocute',
    'IYDKMIGTHTKY (Gimme That)',
    'Angry Inch',
    'Anesthesia',
    'Drunk in Paris',
    'The Dream Is Dead',
    // Trivium
    'The End Of Everything',
    'Rain',
    'Pull Harder On The Strings Of Your Martyr',
    'Drowned And Torn Asunder',
    'Ascendancy',
    'A Gunshot To The Head Of Trepidation',
    'Like Light To The Flies',
    'Dying In Your Arms',
    'The Deceived',
    'Suffocating Sight',
    'Departure',
    'Declaration',
    'Ignition',
    'Detonation',
    'Entrance Of The Conflagration',
    'Anthem (We Are The Fire)',
    'Unrepentant',
    'And Sadness Will Sear',
    'Becoming The Dragon',
    'To The Rats',
    'This World Can\'t Tear Us Apart',
    'Tread The Floods',
    'Contempt Breeds Contamination',
    'The Rising',
    'The Crusade',
    'Kirisute Gomen',
    'Torn Between Scylla and Charybdis',
    'Down From The Sky',
    'Into The Mouth Of Hell We March',
    'Throes Of Perdition',
    'Insurrection',
    'The Calamity',
    'He Who Spawned The Furies',
    'Of Prometheus And The Crucifix',
    'Like Callisto To A Star In Heaven',
    'Shogun',
    'Capsizing The Sea',
    'In Waves',
    'Inception Of The End',
    'Dusk Dismantled',
    'Watch The World Burn',
    'Black',
    'A Skyline\'s Severance',
    'Ensnare The Sun',
    'Built To Fall',
    'Caustic Are The Ties That Bind',
    'Forsake Not The Dream',
    'Drowning In Slow Motion',
    'A Grey So Dark',
    'Chaos Reigns',
    'Of All These Yesterdays',
    'Leaving This World Behind',
    'Shattering The Skies Above',
    'Brave This Storm',
    'Vengeance Falls',
    'Strife',
    'No Way To Heal',
    'To Believe',
    'At The End Of This War',
    'Through Blood And Dirt And Bone',
    'Villainy Thrives',
    'Incineration_ The Broken World',
    'Wake (The End Is Nigh)',
    'No Hope For The Human Race',
    'As I Am Exploding',
    'Skulls...We Are 138',
    'Snofall',
    'Silence In the Snow',
    'Blind Leading The Blind',
    'Dead And Gone',
    'The Ghost That\'s Haunting You',
    'Pull Me From The Void',
    'Until The World Goes Cold',
    'Rise Above The Tides',
    'The Thing That\'s Killing',
    'Beneath The Sun',
    'Breathe In The Flames',
    'Cease All Your Fire',
    'The Darkness Of My Mind',
    'The Sin And The Sentence',
    'Beyond Oblivion',
    'Other Worlds',
    'The Heart From Your Hate',
    'Betrayer',
    'The Wretchedness Inside',
    'Endless Night',
    'Sever The Hand',
    'Beauty In The Sorrow',
    'The Revanchist',
    'Thrown Into The Fire',
    'IX',
    'What The Dead Men Say',
    'Catastrophist',
    'Amongst The Shadows & The Stones',
    'Bleed Into Me',
    'The Defiant',
    'Sickness Unto You',
    'Scattering The Ashes',
    'Bending The Arc To Fear',
    'The Ones We Leave Behind',
    // Sepultura
    'Refuse / Resist',
    'Territory',
    'Slave New World',
    'Amen',
    'Kaiowas',
    'Propaganda',
    'Biotech Is Godzilla',
    'Nomad',
    'We Who Are Not As Others',
    'Manifest',
    'The Hunt',
    'Clenched Fist',
    'Chaos B.C.',
    'Roots Bloody Roots',
    'Attitude',
    'Cut-Throat',
    'Ratamahatta',
    'Breed Apart',
    'Straighthate',
    'Spit',
    'Lookaway',
    'Dusted',
    'Born Stubborn',
    'Jasco',
    'Itsari',
    'Ambush',
    'Endangered Species',
    'Dictatorshit',
    'Canyon Jam',
    // Fleshgod Apocalypse
    'Temptation',
    'The Hypocrisy',
    'The Imposition',
    'The Deceit',
    'The Violation',
    'The Egoism',
    'The Betrayal',
    'The Forsaking',
    'The Oppression',
    'Agony',
    'Kingborn',
    'Minotaur (The Wrath Of Poseidon)',
    'Elegy',
    'Towards The Sun',
    'Warpledge',
    'Pathfinder',
    'The Fall Of Asterion',
    'Prologue',
    'Epilogue',
    'Under Black Sails',
    'Labyrinth',
    'Marche Royale',
    'In Aeternum',
    'Healing Through War',
    'The Fool',
    'Cold As Perfection',
    'Mitra',
    'Paramour (Die Leidenschaft Bringt Leiden)',
    'And The Vulture Beholds',
    'Gravity',
    'A Million Deaths',
    'Syphilis',
    'King',
    'Fury',
    'Carnivorous Lamb',
    'Sugar',
    'The Praying Mantis\' Strategy',
    'Monnalisa',
    'Worship and Forget',
    'Absinthe',
    'Pissing on the Score',
    'The Day We\'ll Be Gone',
    'Embrace the Oblivion',
    'Veleno',
    'Reise, Reise',
    // Suicidal Tendencies
    'You Can\'t Bring Me Down',
    'Lost Again',
    'Alone',
    'Lovely',
    'Give It Revolution',
    'Get Whacked',
    'Send Me Your Money',
    'Emotion No. 13',
    'Disco\'s Out, Murder\'s In',
    'Go\'N Breakdown',
    'Can\'t Stop',
    'Accept My Sacrifice',
    'Nobody Hears',
    'Tap Into The Power',
    'Monopoly On Sorrow',
    'We Call This Mutha Revenge',
    'I Wasn\'t Meant To Feel This (Asleep At The Wheel)',
    'Gotta Kill Captain Stupid',
    'I\'ll Hate You Better',
    'Which Way To Free',
    'It\'s Going Down',
    'Where\'s The Truth',
    // ...And You Will Know Us By The Trail Of Dead
    'Richter Scale Madness',
    'Novena Without Faith',
    'Fare Fare Eyes',
    'Half Of What',
    'Gargoyle Waiting',
    'Prince With A Thousand Enemies',
    'Ounce Of Prevention',
    'When We Begin To Steal...',
    'Invocation',
    'It Was There That I Saw You',
    'Another Morning Stoner',
    'Baudelaire',
    'Homage',
    'How Near How Far',
    'Life Is Elsewhere',
    'Heart In The Hand Of The Matter',
    'Monsoon',
    'Days Of Being Wild',
    'Relative Ways',
    'After The Laughter',
    'Source Tags & Codes',
    'Overture',
    'Will You Smile Again For Me',
    'World\'s Apart',
    'The Summer Of \'91',
    'The Rest Will Follow',
    'Caterwaul',
    'A Classic Arts Showcase',
    'Let It Dive',
    'All White',
    'The Best',
    'City Of Refuge',
    'Stand In Silence',
    'Wasted State Of Mind',
    'Naked Sun',
    'Gold Heart Mountain Top Queen Directory',
    'So Divided',
    'Eight Day Hell',
    'Witch\'s Web',
    'Segue Way In The Realms Of The Unreal',
    'Sunken Dreams',
    'Pure Radio Cosplay',
    'Summer Of All Dead Souls',
    'Cover The Days Like A Tidal Wave',
    'Fall Of The Empire',
    'The Wasteland',
    'Spiral Jetty',
    'Weight Of The Sun (Or The Post-Modern Prometheus)',
    'Ebb Away',
    'The Fairlight Pendant',
    'Tao Of The Dead Part Two: Strange News From Another Planet',
    'Open Doors',
    'Pinhole Cameras',
    'Up to Infinity',
    'Opera Obscura',
    'Lost Songs',
    'Flower Card Games',
    'A Place to Rest',
    'Heart of Wires',
    'Catatonic',
    'Awestruck',
    'Bright Young Things',
    'Time and Again',
    'The Doomsday Book',
    'Jaded Apostles',
    'A Million Random Digits',
    'Lie Without A Liar',
    'The Ghost Within',
    'The Dragonfly Queen',
    'How To Avoid Huge Ships',
    'Bus Lines',
    'Lost In The Grand Scheme',
    'Like Summer Tempests Came His Tears',
    'Sound Of The Silk',

];
